services:
  - type: web
    name: odnix-backend
    env: python
    buildCommand: "bash build.sh"
    startCommand: "daphne odnix.asgi:application --port $PORT --bind 0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DB_ENCRYPTION_KEY
        generateValue: true
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: ENABLE_PHONE_VERIFICATION
        value: "True"
      - key: DEBUG
        value: "False"
