# Generated by Django 5.0 on 2026-03-21 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0044_customuser_bio_customuser_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='omzocomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chat.omzocomment'),
        ),
    ]
