# Generated by Django 5.0 on 2026-03-24 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0046_customuser_is_phone_verified_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverificationtoken',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='phoneverificationtoken',
            name='registration_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phoneverificationtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
