# Generated by Django 4.2.7 on 2026-04-16 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0047_phoneverificationtoken_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='registration_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
