# Generated by Django 4.2.7 on 2026-04-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0048_emailverificationtoken_email_and_more'),
        ('chat', '0049_add_private_chat_ids_to_user'),
    ]

    operations = [
    ]
