# Generated by Django 4.2.7 on 2026-04-19 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0050_merge_20260419_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmzoCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('omzo_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omzo_comment_likes', to='chat.omzocomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_omzo_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('user', 'omzo_comment')},
            },
        ),
    ]
