# Generated by Django 4.2.7 on 2026-04-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0051_omzocommentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='group_avatar',
            field=models.FileField(blank=True, null=True, upload_to='group_avatars/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='cover_pics/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='scribe',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='scribe_images/'),
        ),
    ]
